"""T1-01 contracts: dependency lock files (P0-06 CPU/CUDA split).

``requirements.in`` / ``requirements-optional.in`` are the human spec;
``requirements.txt`` / ``requirements-optional.txt`` are the generated
exact pins; ``requirements.lock`` is the full frozen environment snapshot.
All three are generated by ``scripts/freeze_lock.py`` and must stay in sync
with the environment that produced them (``--check`` gate).

P0-06 contract: the base pin files always carry the **CPU** torch wheel
(``<base>+cpu``), regardless of the local torch build — a clean
environment and CI never depend on a CUDA wheel.  ``requirements-cuda.txt``
is the hand-maintained GPU replacement for the torch pin; its torch base
version must match ``requirements.txt`` and its pin must be a CUDA wheel.
Torch is therefore the only package whose pin is not required to equal the
installed version verbatim (its base version must still match).
"""

from __future__ import annotations

import re
import subprocess
import sys
from importlib import metadata
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
PIN_RE = re.compile(r"^([A-Za-z0-9_.\-]+)(\[[^\]]+\])?==([^=]+)$")

REQUIREMENT_FILES = (
    ROOT / "requirements.in",
    ROOT / "requirements.txt",
    ROOT / "requirements-optional.in",
    ROOT / "requirements-optional.txt",
    ROOT / "requirements.lock",
)


def _lines(path: Path) -> list[str]:
    return [
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]


def _pins(path: Path) -> list[str]:
    """Non-directive lines (pip index options are not pins)."""

    return [line for line in _lines(path) if not line.startswith("--")]


def _torch_pin(path: Path) -> str:
    return next(
        line for line in _pins(path) if line.startswith("torch==")
    )


@pytest.fixture(scope="module", autouse=True)
def _lock_files_exist():
    for path in REQUIREMENT_FILES:
        assert path.exists(), f"missing lock artifact: {path.name}"
    assert (ROOT / "requirements-cuda.txt").exists(), (
        "missing lock artifact: requirements-cuda.txt (P0-06 GPU replacement)"
    )


def test_spec_files_exist_and_are_unpinned():
    for name in ("requirements.in", "requirements-optional.in"):
        for line in _lines(ROOT / name):
            assert "==" not in line, f"{name} must stay a spec: {line}"


def test_pinned_files_use_exact_versions():
    for name in ("requirements.txt", "requirements-optional.txt"):
        for line in _lines(ROOT / name):
            if line.startswith("--"):
                # pip index directive (P0-06): the CPU torch wheel lives on
                # the PyTorch CPU index, not on PyPI.
                assert line.startswith("--extra-index-url "), line
        for line in _pins(ROOT / name):
            assert PIN_RE.match(line), f"not an exact pin: {line}"
            assert ">=" not in line and "~=" not in line


def test_pins_match_installed_environment():
    for name in ("requirements.txt", "requirements-optional.txt"):
        for line in _pins(ROOT / name):
            match = PIN_RE.match(line)
            assert match, line
            package = match.group(1)
            installed = metadata.version(package)
            pinned = match.group(3)
            if package == "torch":
                # P0-06: the base pin is the CPU wheel of the installed
                # base version; a local CUDA torch is a machine-specific
                # replacement and must never leak into the base file.
                assert pinned.endswith("+cpu"), f"base pin must be the CPU wheel: {line}"
                assert pinned.split("+")[0] == installed.split("+")[0], (
                    f"torch: pinned base {pinned.split('+')[0]} but installed "
                    f"base {installed.split('+')[0]}"
                )
            else:
                assert installed == pinned, (
                    f"{package}: pinned {pinned} but installed {installed}"
                )


def test_cuda_replacement_file_consistent():
    base = _torch_pin(ROOT / "requirements.txt")
    cuda = _torch_pin(ROOT / "requirements-cuda.txt")
    assert base.split("+")[0] == cuda.split("+")[0], (
        f"requirements-cuda.txt torch base version must match requirements.txt "
        f"({base} vs {cuda})"
    )
    assert cuda.endswith("+cu128") or re.search(r"\+cu[0-9]+$", cuda), (
        f"requirements-cuda.txt must pin a CUDA wheel, got: {cuda}"
    )
    assert base.endswith("+cpu"), f"base torch pin must be the CPU wheel: {base}"


def test_spec_packages_are_covered_by_pins():
    pinned = {
        PIN_RE.match(line).group(1)
        for name in ("requirements.txt", "requirements-optional.txt")
        for line in _pins(ROOT / name)
    }
    for name in ("requirements.in", "requirements-optional.in"):
        for line in _lines(ROOT / name):
            package = line.split("[")[0].split("==")[0].strip()
            assert package in pinned, f"spec package {package} not pinned"


def test_lock_file_is_a_full_freeze():
    locked = _lines(ROOT / "requirements.lock")
    assert len(locked) > 50  # a full freeze covers the transitive closure
    for line in locked:
        assert PIN_RE.match(line), f"not a pinned line: {line}"
    pinned_names = {
        PIN_RE.match(line).group(1)
        for name in ("requirements.txt", "requirements-optional.txt")
        for line in _pins(ROOT / name)
    }
    locked_names = {PIN_RE.match(line).group(1) for line in locked}
    assert pinned_names <= locked_names


def test_freeze_lock_check_passes():
    proc = subprocess.run(
        [sys.executable, "scripts/freeze_lock.py", "--check"],
        cwd=ROOT,
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 0, proc.stdout + proc.stderr
