"""T1-01 contracts: dependency lock files (P0-06 CPU/CUDA split).

``requirements.in`` / ``requirements-optional.in`` are the human spec;
``requirements.txt`` / ``requirements-optional.txt`` are the generated
exact pins; ``requirements.lock`` is the full frozen environment snapshot.
All three are generated by ``scripts/freeze_lock.py`` and must stay in sync
with the environment that produced them (``--check`` gate).

P0-06 contract: the base pin files always carry the **CPU** torch wheel
(``<base>+cpu``), regardless of the local torch build — a clean
environment and CI never depend on a CUDA wheel.  ``requirements-cuda.txt``
is the hand-maintained GPU replacement for the torch pin; its torch base
version must match ``requirements.txt`` and its pin must be a CUDA wheel.
Torch is therefore the only package whose pin is not required to equal the
installed version verbatim (its base version must still match).

IP-04 (03-F-01) additions: ``scripts/lock_audit.py`` is the read-only
lock<->installed-environment drift reporter.  ``requirements.lock`` is the
frozen closure of the clean CI-faithful environment that last ran
``scripts/freeze_lock.py`` — it is NOT a live snapshot of any given dev
machine — so the drift it accumulates silently is made visible here: unit
tests pin the tool's diff/exit-code contract, one subprocess test proves the
read-only CLI behavior, and the opt-in dev-machine guard
(``ALPHAGPT_LOCK_AUDIT_STRICT=1``) turns drift into a test failure on
machines that opted into lock-faithfulness.  CI installs the pin files and
never ``requirements.lock``, so the guard's skip is the registered IP-04
dev-machine-only baseline skip (invalidation: a CI job that installs the
lock would remove the reason for the skip).
"""

from __future__ import annotations

import importlib.util
import os
import re
import subprocess
import sys
from importlib import metadata
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
PIN_RE = re.compile(r"^([A-Za-z0-9_.\-]+)(\[[^\]]+\])?==([^=]+)$")

REQUIREMENT_FILES = (
    ROOT / "requirements.in",
    ROOT / "requirements.txt",
    ROOT / "requirements-optional.in",
    ROOT / "requirements-optional.txt",
    ROOT / "requirements.lock",
)


def _lines(path: Path) -> list[str]:
    return [
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]


def _pins(path: Path) -> list[str]:
    """Non-directive lines (pip index options are not pins)."""

    return [line for line in _lines(path) if not line.startswith("--")]


def _torch_pin(path: Path) -> str:
    return next(
        line for line in _pins(path) if line.startswith("torch==")
    )


@pytest.fixture(scope="module", autouse=True)
def _lock_files_exist():
    for path in REQUIREMENT_FILES:
        assert path.exists(), f"missing lock artifact: {path.name}"
    assert (ROOT / "requirements-cuda.txt").exists(), (
        "missing lock artifact: requirements-cuda.txt (P0-06 GPU replacement)"
    )


def test_spec_files_exist_and_are_unpinned():
    for name in ("requirements.in", "requirements-optional.in"):
        for line in _lines(ROOT / name):
            assert "==" not in line, f"{name} must stay a spec: {line}"


def test_pinned_files_use_exact_versions():
    for name in ("requirements.txt", "requirements-optional.txt"):
        for line in _lines(ROOT / name):
            if line.startswith("--"):
                # pip index directive (P0-06): the CPU torch wheel lives on
                # the PyTorch CPU index, not on PyPI.
                assert line.startswith("--extra-index-url "), line
        for line in _pins(ROOT / name):
            assert PIN_RE.match(line), f"not an exact pin: {line}"
            assert ">=" not in line and "~=" not in line


def test_pins_match_installed_environment():
    for name in ("requirements.txt", "requirements-optional.txt"):
        for line in _pins(ROOT / name):
            match = PIN_RE.match(line)
            assert match, line
            package = match.group(1)
            installed = metadata.version(package)
            pinned = match.group(3)
            if package == "torch":
                # P0-06: the base pin is the CPU wheel of the installed
                # base version; a local CUDA torch is a machine-specific
                # replacement and must never leak into the base file.
                assert pinned.endswith("+cpu"), f"base pin must be the CPU wheel: {line}"
                assert pinned.split("+")[0] == installed.split("+")[0], (
                    f"torch: pinned base {pinned.split('+')[0]} but installed "
                    f"base {installed.split('+')[0]}"
                )
            else:
                assert installed == pinned, (
                    f"{package}: pinned {pinned} but installed {installed}"
                )


def test_cuda_replacement_file_consistent():
    base = _torch_pin(ROOT / "requirements.txt")
    cuda = _torch_pin(ROOT / "requirements-cuda.txt")
    assert base.split("+")[0] == cuda.split("+")[0], (
        f"requirements-cuda.txt torch base version must match requirements.txt "
        f"({base} vs {cuda})"
    )
    assert cuda.endswith("+cu128") or re.search(r"\+cu[0-9]+$", cuda), (
        f"requirements-cuda.txt must pin a CUDA wheel, got: {cuda}"
    )
    assert base.endswith("+cpu"), f"base torch pin must be the CPU wheel: {base}"


def test_spec_packages_are_covered_by_pins():
    pinned = {
        PIN_RE.match(line).group(1)
        for name in ("requirements.txt", "requirements-optional.txt")
        for line in _pins(ROOT / name)
    }
    for name in ("requirements.in", "requirements-optional.in"):
        for line in _lines(ROOT / name):
            package = line.split("[")[0].split("==")[0].strip()
            assert package in pinned, f"spec package {package} not pinned"


def test_lock_file_is_a_full_freeze():
    locked = _lines(ROOT / "requirements.lock")
    assert len(locked) > 50  # a full freeze covers the transitive closure
    for line in locked:
        assert PIN_RE.match(line), f"not a pinned line: {line}"
    pinned_names = {
        PIN_RE.match(line).group(1)
        for name in ("requirements.txt", "requirements-optional.txt")
        for line in _pins(ROOT / name)
    }
    locked_names = {PIN_RE.match(line).group(1) for line in locked}
    assert pinned_names <= locked_names


def test_freeze_lock_check_passes():
    proc = subprocess.run(
        [sys.executable, "scripts/freeze_lock.py", "--check"],
        cwd=ROOT,
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 0, proc.stdout + proc.stderr


# ---------------------------------------------------------------------------
# IP-04 (03-F-01): read-only lock <-> installed-environment audit tool.
# ---------------------------------------------------------------------------

_LOCK_AUDIT_PATH = ROOT / "scripts" / "lock_audit.py"
_LOCK_AUDIT_STRICT_ENV = "ALPHAGPT_LOCK_AUDIT_STRICT"


def _load_lock_audit():
    assert _LOCK_AUDIT_PATH.exists(), (
        "scripts/lock_audit.py missing: the IP-04 read-only lock<->env audit tool"
    )
    spec = importlib.util.spec_from_file_location(
        "lock_audit_under_test", _LOCK_AUDIT_PATH
    )
    module = importlib.util.module_from_spec(spec)
    # dataclasses resolves field annotations through sys.modules[module_name];
    # register before exec_module per the importlib module-from-spec recipe.
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _write_lock(tmp_path: Path, lines: list[str]) -> Path:
    lock_path = tmp_path / "requirements.lock"
    lock_path.write_text(
        "# Generated by scripts/freeze_lock.py from the installed environment.\n"
        + "\n".join(lines)
        + "\n",
        encoding="utf-8",
    )
    return lock_path


def test_lock_audit_diff_buckets_directions_and_by_design_torch():
    # packaging is part of the lock closure (requirements.lock pins it), so
    # the PEP 440 direction is asserted directly.
    lock_audit = _load_lock_audit()
    lock = {
        "alpha": ("alpha", "1.1.0"),
        "beta": ("beta", "2.0.0"),
        "delta": ("delta", "4.0.0"),
        "torch": ("torch", "2.0.0+cpu"),
    }
    env = {
        "alpha": ("alpha", "1.0.0"),
        "beta": ("beta", "2.5.0"),
        "torch": ("torch", "2.0.0+cu128"),
        "gamma": ("gamma", "3.0.0"),
    }
    report = lock_audit.diff_lock_env(lock, env)
    assert [(m.package, m.lock_version, m.env_version, m.direction) for m in report.mismatches] == [
        ("alpha", "1.1.0", "1.0.0", "lock_newer"),
        ("beta", "2.0.0", "2.5.0", "env_newer"),
    ]
    assert report.lock_only == ("delta",)
    assert report.env_only == ("gamma",)
    # torch: equal base versions with different local wheel tags are the
    # P0-06 by-design case (base pins carry +cpu, GPU machines install
    # +cuNN), reported but not drift.
    assert report.torch_local_tag_diffs == (("torch", "2.0.0+cpu", "2.0.0+cu128"),)
    assert report.has_drift is True


def test_lock_audit_torch_base_mismatch_is_drift():
    lock_audit = _load_lock_audit()
    report = lock_audit.diff_lock_env(
        {"torch": ("torch", "2.1.0+cpu")}, {"torch": ("torch", "2.0.0+cu128")}
    )
    assert [(m.package, m.lock_version, m.env_version) for m in report.mismatches] == [
        ("torch", "2.1.0+cpu", "2.0.0+cu128")
    ]
    assert report.torch_local_tag_diffs == ()
    assert report.has_drift is True


def test_lock_audit_parse_lock_lines_fail_closed_on_unparsed():
    lock_audit = _load_lock_audit()
    pins, unparsed = lock_audit.parse_lock_lines(
        ["alpha==1.0", "# comment", "--extra-index-url https://example", "not-a-pin-line"]
    )
    assert pins == {"alpha": ("alpha", "1.0")}
    assert unparsed == ["not-a-pin-line"]


def test_lock_audit_main_in_sync_exit_zero_and_writes_nothing(tmp_path, monkeypatch):
    lock_audit = _load_lock_audit()
    _write_lock(tmp_path, ["alpha==1.0.0"])
    monkeypatch.setattr(lock_audit, "ROOT", tmp_path)
    monkeypatch.setattr(lock_audit, "installed_map", lambda: {"alpha": ("alpha", "1.0.0")})
    before = sorted(p.name for p in tmp_path.iterdir())
    assert lock_audit.main([]) == 0
    assert sorted(p.name for p in tmp_path.iterdir()) == before


def test_lock_audit_main_drift_exit_one_reports_all_buckets(tmp_path, monkeypatch, capsys):
    lock_audit = _load_lock_audit()
    _write_lock(tmp_path, ["alpha==1.1.0", "beta==2.0.0"])
    monkeypatch.setattr(lock_audit, "ROOT", tmp_path)
    monkeypatch.setattr(
        lock_audit,
        "installed_map",
        lambda: {"alpha": ("alpha", "1.0.0"), "gamma": ("gamma", "3.0.0")},
    )
    assert lock_audit.main([]) == 1
    out = capsys.readouterr().out
    assert "alpha" in out and "1.1.0" in out and "1.0.0" in out  # mismatch pair
    assert "beta" in out  # lock-only
    assert "gamma" in out  # env-only


def test_lock_audit_main_missing_lock_exit_two(tmp_path, monkeypatch):
    lock_audit = _load_lock_audit()
    monkeypatch.setattr(lock_audit, "ROOT", tmp_path)
    assert lock_audit.main([]) == 2


def test_lock_audit_cli_runs_read_only_against_repo():
    proc = subprocess.run(
        [sys.executable, "scripts/lock_audit.py"],
        cwd=ROOT,
        capture_output=True,
        text=True,
    )
    assert proc.returncode in (0, 1), proc.stdout + proc.stderr
    assert "lock audit" in proc.stdout


@pytest.mark.skipif(
    os.environ.get(_LOCK_AUDIT_STRICT_ENV) != "1",
    reason=(
        "dev-machine-only guard (IP-04 / 03-F-01 baseline skip): compares "
        "requirements.lock against the installed environment of the running "
        "interpreter.  CI installs the pin files and never requirements.lock, "
        "so the comparison is meaningless there.  Opt in on a lock-faithful "
        "dev machine with ALPHAGPT_LOCK_AUDIT_STRICT=1."
    ),
)
def test_lock_matches_installed_environment_dev_machine():
    lock_audit = _load_lock_audit()
    assert lock_audit.main([]) == 0, (
        "lock<->environment drift detected (see the audit report above); "
        "align the environment per package via the authorized command list — "
        "never `pip install -r requirements.lock` wholesale (the +cpu torch "
        "pin would override a locally installed CUDA torch)."
    )
