"""T1-01 contracts: dependency lock files.

``requirements.in`` / ``requirements-optional.in`` are the human spec;
``requirements.txt`` / ``requirements-optional.txt`` are the generated
exact pins; ``requirements.lock`` is the full frozen environment snapshot.
All three are generated by ``scripts/freeze_lock.py`` and must stay in sync
with the environment that produced them (``--check`` gate).
"""

from __future__ import annotations

import re
import subprocess
import sys
from importlib import metadata
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
PIN_RE = re.compile(r"^([A-Za-z0-9_.\-]+)(\[[^\]]+\])?==([^=]+)$")

REQUIREMENT_FILES = (
    ROOT / "requirements.in",
    ROOT / "requirements.txt",
    ROOT / "requirements-optional.in",
    ROOT / "requirements-optional.txt",
    ROOT / "requirements.lock",
)


def _lines(path: Path) -> list[str]:
    return [
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]


@pytest.fixture(scope="module", autouse=True)
def _lock_files_exist():
    for path in REQUIREMENT_FILES:
        assert path.exists(), f"missing lock artifact: {path.name}"


def test_spec_files_exist_and_are_unpinned():
    for name in ("requirements.in", "requirements-optional.in"):
        for line in _lines(ROOT / name):
            assert "==" not in line, f"{name} must stay a spec: {line}"


def test_pinned_files_use_exact_versions():
    for name in ("requirements.txt", "requirements-optional.txt"):
        for line in _lines(ROOT / name):
            assert PIN_RE.match(line), f"not an exact pin: {line}"
            assert ">=" not in line and "~=" not in line


def test_pins_match_installed_environment():
    for name in ("requirements.txt", "requirements-optional.txt"):
        for line in _lines(ROOT / name):
            match = PIN_RE.match(line)
            assert match, line
            package = match.group(1)
            installed = metadata.version(package)
            assert installed == match.group(3), (
                f"{package}: pinned {match.group(3)} but installed {installed}"
            )


def test_spec_packages_are_covered_by_pins():
    pinned = {
        PIN_RE.match(line).group(1)
        for name in ("requirements.txt", "requirements-optional.txt")
        for line in _lines(ROOT / name)
    }
    for name in ("requirements.in", "requirements-optional.in"):
        for line in _lines(ROOT / name):
            package = line.split("[")[0].split("==")[0].strip()
            assert package in pinned, f"spec package {package} not pinned"


def test_lock_file_is_a_full_freeze():
    locked = _lines(ROOT / "requirements.lock")
    assert len(locked) > 50  # a full freeze covers the transitive closure
    for line in locked:
        assert PIN_RE.match(line), f"not a pinned line: {line}"
    pinned_names = {
        PIN_RE.match(line).group(1)
        for name in ("requirements.txt", "requirements-optional.txt")
        for line in _lines(ROOT / name)
    }
    locked_names = {PIN_RE.match(line).group(1) for line in locked}
    assert pinned_names <= locked_names


def test_freeze_lock_check_passes():
    proc = subprocess.run(
        [sys.executable, "scripts/freeze_lock.py", "--check"],
        cwd=ROOT,
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 0, proc.stdout + proc.stderr
