"""Dependency lock generator (T1-01, CPU/CUDA split P0-06).

The repo uses the spec/lock convention instead of lower-bound-only
requirements:

* ``requirements.in`` / ``requirements-optional.in`` — the human spec
  (plain package names; the contract of what the project needs).
* ``requirements.txt`` / ``requirements-optional.txt`` — exact pins of the
  spec packages, generated from the *installed* environment (this is what
  CI installs, so CI is reproducible).
* ``requirements-cuda.txt`` — hand-maintained GPU replacement for the
  torch pin (P0-06): the base files always carry the **CPU** torch wheel,
  so a clean environment and CI never depend on a CUDA wheel; machines
  with an NVIDIA GPU replace torch via this file.  ``--check`` verifies
  its torch base version stays aligned with ``requirements.txt``.
* ``requirements.lock`` — the full frozen closure (every installed
  distribution, captured via ``importlib.metadata`` from the interpreter
  that last ran this script).  The committed lock is a snapshot of that
  generating environment — a clean CI-faithful venv (provenance:
  ``docs/test_runtime_measurement_log.md``).  It matches **neither**
  persistent local environment of a development machine (e.g. a GPU
  development environment with a CUDA torch, or a separate CPU
  environment used to produce gate evidence); the environment identity
  behind a piece of evidence comes from the per-run records in the
  measurement logs, not from this lock.  Do **not** reproduce a machine
  with ``pip install -r requirements.lock``: the torch pin in the lock
  is the ``+cpu`` wheel (P0-06) and wholesale installation would
  override a locally installed CUDA torch (observed with
  ``2.11.0+cu128``).  Developer machines review lock<->environment
  drift with the read-only ``scripts/lock_audit.py`` — run it under
  each local interpreter to audit every environment separately — and
  align per package via individually authorized commands.

Usage:
    python scripts/freeze_lock.py            # regenerate all lock files
    python scripts/freeze_lock.py --check    # verify pin files match the env
    python scripts/freeze_lock.py --check-full  # also verify the full lock

``--check`` exits 1 when any generated *pin* file differs from the
committed one, so CI can gate on lock drift (the pin files are portable:
CI installs exactly those pins, so the check passes there).  The full
``requirements.lock`` is the snapshot of the environment that generated it
(platform-specific packages included); ``--check-full`` additionally
verifies it and is meaningful on a machine whose installed environment
matches that closure (clean CI-faithful venvs, or a dev machine after an
authorized per-package alignment).  On other machines use the read-only
``scripts/lock_audit.py`` to report the drift instead.  Regeneration is
deterministic: pins come from ``importlib.metadata`` of the current
interpreter.

Torch normalization (P0-06): the installed torch on a GPU machine carries
a CUDA local version (e.g. ``2.11.0+cu128``), but the base pin file must
stay CPU-only, so the generated torch pin is always the CPU wheel of the
same base version (``<base>+cpu``) and the file carries the PyTorch CPU
index directive required to resolve it.  GPU machines replace the torch
pin through ``requirements-cuda.txt``.
"""

from __future__ import annotations

import argparse
import importlib.metadata
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HEADER = "# Generated by scripts/freeze_lock.py from the installed environment.\n"

SPEC_FILES = {
    "requirements.in": "requirements.txt",
    "requirements-optional.in": "requirements-optional.txt",
}
LOCK_FILE = "requirements.lock"

# P0-06 CPU/CUDA split: the base pin files always carry the CPU torch
# wheel (clean environments and CI consume the base files); machines with
# an NVIDIA GPU replace the torch pin through ``requirements-cuda.txt``.
# The generated requirements.txt therefore carries the PyTorch CPU index
# directive (PyPI does not host ``+cpu`` local-version wheels).
_TORCH_CPU_SUFFIX = "+cpu"
_TORCH_CPU_INDEX = "--extra-index-url https://download.pytorch.org/whl/cpu"
CUDA_FILE = "requirements-cuda.txt"


def _spec_packages(spec_path: Path) -> list[str]:
    """Plain package names from a spec file (comments/blank lines skipped)."""

    packages = []
    for line in spec_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        name = re.split(r"[\[=<>~!]", line, maxsplit=1)[0].strip()
        if name:
            packages.append(name)
    return packages


def _pin(package: str) -> str:
    version = importlib.metadata.version(package)
    if package == "torch":
        # P0-06: never mirror a local CUDA torch (e.g. 2.11.0+cu128) into
        # the CPU base pin; pin the CPU wheel of the same base version so
        # the base files stay CUDA-free by construction.
        version = version.split("+", 1)[0] + _TORCH_CPU_SUFFIX
    return f"{package}=={version}"


def _generated_text(spec_path: Path) -> str:
    packages = _spec_packages(spec_path)
    lines = [HEADER]
    if "torch" in packages:
        lines.append(
            "# CPU-base torch wheel (P0-06): the base files never depend on a\n"
            "# CUDA wheel; GPU machines replace torch via requirements-cuda.txt."
        )
        lines.append(_TORCH_CPU_INDEX)
    for package in packages:
        lines.append(_pin(package))
    return "\n".join(lines) + "\n"


def _torch_base_version(pin_line: str) -> str | None:
    """Base version of a ``torch==X.Y.Z+local`` pin line, or ``None``."""

    match = re.match(r"^torch==([0-9][^+]*)\+", pin_line)
    return match.group(1) if match else None


def _verify_cuda_file(root: Path, base_pin: str) -> list[str]:
    """Cross-check the hand-maintained CUDA replacement pin file.

    ``requirements-cuda.txt`` is machine-specific by design (it replaces
    the CPU torch pin with the CUDA wheel), so it is not regenerated here;
    ``--check`` only verifies it stays coherent with the base file: the
    torch base version must match and the pin must be a CUDA wheel.
    """

    failures = []
    path = root / CUDA_FILE
    if not path.exists():
        failures.append(f"{CUDA_FILE} is missing")
        return failures
    base_version = _torch_base_version(base_pin)
    cuda_pin = next(
        (
            line.strip()
            for line in path.read_text(encoding="utf-8").splitlines()
            if line.strip().startswith("torch==")
        ),
        None,
    )
    if cuda_pin is None:
        failures.append(f"{CUDA_FILE} has no torch pin")
        return failures
    cuda_version = _torch_base_version(cuda_pin)
    if base_version is not None and cuda_version != base_version:
        failures.append(
            f"{CUDA_FILE} torch base version {cuda_version} does not match "
            f"the requirements.txt torch base version {base_version}"
        )
    if not re.search(r"\+cu[0-9]+$", cuda_pin):
        failures.append(f"{CUDA_FILE} torch pin is not a CUDA wheel: {cuda_pin}")
    return failures


def _full_freeze() -> str:
    dists = sorted(
        importlib.metadata.distributions(),
        key=lambda d: (d.metadata["Name"] or "").lower(),
    )
    lines = [
        f"{d.metadata['Name']}=={d.version}"
        for d in dists
        if d.metadata["Name"]
    ]
    return HEADER + "\n".join(lines) + "\n"


def generate() -> dict[str, str]:
    """Return ``{relative_path: generated_text}`` for every lock artifact."""

    outputs = {}
    for spec_name, pin_name in SPEC_FILES.items():
        outputs[pin_name] = _generated_text(ROOT / spec_name)
    outputs[LOCK_FILE] = _full_freeze()
    return outputs


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed pin files match the installed environment",
    )
    parser.add_argument(
        "--check-full",
        action="store_true",
        help="also verify the full requirements.lock snapshot (dev machines)",
    )
    args = parser.parse_args(argv)

    outputs = generate()
    if args.check or args.check_full:
        checked = (
            list(outputs)
            if args.check_full
            else [pin_name for pin_name in SPEC_FILES.values()]
        )
        failures = []
        for name in checked:
            path = ROOT / name
            if not path.exists() or path.read_text(encoding="utf-8") != outputs[name]:
                failures.append(name)
        if "requirements.txt" in checked:
            failures.extend(_verify_cuda_file(ROOT, outputs["requirements.txt"]))
        if failures:
            print(
                "lock drift: regenerate with `python scripts/freeze_lock.py`: "
                + ", ".join(failures),
                file=sys.stderr,
            )
            return 1
        scope = "full lock" if args.check_full else "pin files"
        print(f"{scope} are in sync with the installed environment")
        return 0

    for name, text in outputs.items():
        (ROOT / name).write_text(text, encoding="utf-8")
        print(f"wrote {name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
