"""Dependency lock generator (T1-01).

The repo uses the spec/lock convention instead of lower-bound-only
requirements:

* ``requirements.in`` / ``requirements-optional.in`` — the human spec
  (plain package names; the contract of what the project needs).
* ``requirements.txt`` / ``requirements-optional.txt`` — exact pins of the
  spec packages, generated from the *installed* environment (this is what
  CI installs, so CI is reproducible).
* ``requirements.lock`` — the full frozen environment (every installed
  distribution, generated via ``importlib.metadata``; equivalent to a
  ``pip freeze`` snapshot).  Developer machines reproduce the working
  environment with ``pip install -r requirements.lock``.

Usage:
    python scripts/freeze_lock.py            # regenerate all lock files
    python scripts/freeze_lock.py --check    # verify pin files match the env
    python scripts/freeze_lock.py --check-full  # also verify the full lock

``--check`` exits 1 when any generated *pin* file differs from the
committed one, so CI can gate on lock drift (the pin files are portable:
CI installs exactly those pins, so the check passes there).  The full
``requirements.lock`` is a developer-machine snapshot (platform-specific
packages included); ``--check-full`` additionally verifies it and is meant
for the machine that generated it.  Regeneration is deterministic: pins
come from ``importlib.metadata`` of the current interpreter.
"""

from __future__ import annotations

import argparse
import importlib.metadata
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HEADER = "# Generated by scripts/freeze_lock.py from the installed environment.\n"

SPEC_FILES = {
    "requirements.in": "requirements.txt",
    "requirements-optional.in": "requirements-optional.txt",
}
LOCK_FILE = "requirements.lock"


def _spec_packages(spec_path: Path) -> list[str]:
    """Plain package names from a spec file (comments/blank lines skipped)."""

    packages = []
    for line in spec_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        name = re.split(r"[\[=<>~!]", line, maxsplit=1)[0].strip()
        if name:
            packages.append(name)
    return packages


def _pin(package: str) -> str:
    return f"{package}=={importlib.metadata.version(package)}"


def _generated_text(spec_path: Path) -> str:
    lines = [HEADER]
    for package in _spec_packages(spec_path):
        lines.append(_pin(package))
    return "\n".join(lines) + "\n"


def _full_freeze() -> str:
    dists = sorted(
        importlib.metadata.distributions(),
        key=lambda d: (d.metadata["Name"] or "").lower(),
    )
    lines = [
        f"{d.metadata['Name']}=={d.version}"
        for d in dists
        if d.metadata["Name"]
    ]
    return HEADER + "\n".join(lines) + "\n"


def generate() -> dict[str, str]:
    """Return ``{relative_path: generated_text}`` for every lock artifact."""

    outputs = {}
    for spec_name, pin_name in SPEC_FILES.items():
        outputs[pin_name] = _generated_text(ROOT / spec_name)
    outputs[LOCK_FILE] = _full_freeze()
    return outputs


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed pin files match the installed environment",
    )
    parser.add_argument(
        "--check-full",
        action="store_true",
        help="also verify the full requirements.lock snapshot (dev machines)",
    )
    args = parser.parse_args(argv)

    outputs = generate()
    if args.check or args.check_full:
        checked = (
            list(outputs)
            if args.check_full
            else [pin_name for pin_name in SPEC_FILES.values()]
        )
        failures = []
        for name in checked:
            path = ROOT / name
            if not path.exists() or path.read_text(encoding="utf-8") != outputs[name]:
                failures.append(name)
        if failures:
            print(
                "lock drift: regenerate with `python scripts/freeze_lock.py`: "
                + ", ".join(failures),
                file=sys.stderr,
            )
            return 1
        scope = "full lock" if args.check_full else "pin files"
        print(f"{scope} are in sync with the installed environment")
        return 0

    for name, text in outputs.items():
        (ROOT / name).write_text(text, encoding="utf-8")
        print(f"wrote {name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
