"""Generate ``docs/feature_registry.md`` from the single registries (P7 D3).

The document is **generated, never hand-edited**: every feature/operator
fact comes from one authority — the authored feature metadata
(:mod:`ashare_model.feature_metadata`), the P6 research domains
(:mod:`ashare_model.research_domain`), the PIT tier mapping
(:mod:`ashare_model.data_tier` via the public
:func:`ashare_model.feature_registry.pit_level_of` path) and the operator
registry (:mod:`ashare_model.operator_registry`, which derives arity from
``OPS_CONFIG``).  Measured quantities (empirical coverage, correlation
clusters) are deliberately excluded: they depend on the calibration data,
not on the declaration.

Usage:
    python scripts/generate_registry_docs.py            # (re)write the doc
    python scripts/generate_registry_docs.py --check    # exit 1 on drift
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# ``python scripts/generate_registry_docs.py`` sets sys.path[0] to scripts/.
_ROOT = Path(__file__).resolve().parents[1]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from ashare_model.factors import FACTOR_REGISTRY
from ashare_model.feature_metadata import (
    FEATURE_METADATA,
    resolve_cost,
    resolve_depends_on,
    resolve_expected_horizon,
)
from ashare_model.feature_registry import (
    FEATURE_REGISTRY_VERSION,
    family_of,
    pit_level_of,
)
from ashare_model.data_tier import DATA_TIER_VERSION, tier_of_pit_level
from ashare_model.operator_registry import OPERATOR_REGISTRY
from ashare_model.research_domain import RESEARCH_DOMAIN_VERSION, RESEARCH_DOMAINS
from ashare_model.ops import OPS_CONFIG
from ashare_model.vocab import FEATURE_NAMES

DOC_PATH = _ROOT / "docs" / "feature_registry.md"

_GENERATED_HEADER = (
    "<!-- GENERATED by scripts/generate_registry_docs.py -- DO NOT EDIT. -->\n"
    "<!-- Regenerate: python scripts/generate_registry_docs.py -->\n"
)


def _feature_domain(name: str) -> str:
    for domain in RESEARCH_DOMAINS.values():
        if name in domain.features:
            return domain.id
    return "(none: deprecated)"


def build_document() -> str:
    """Render the registry reference document (pure; no data needed)."""

    lines: list[str] = []
    add = lines.append

    add("# 因子与算子注册表（生成物）")
    add("")
    add(_GENERATED_HEADER, )
    add(
        f"版本：`FEATURE_REGISTRY_VERSION = {FEATURE_REGISTRY_VERSION}`、"
        f"`DATA_TIER_VERSION = {DATA_TIER_VERSION}`、"
        f"`RESEARCH_DOMAIN_VERSION = {RESEARCH_DOMAIN_VERSION}`。"
    )
    add("")
    add(
        "本文件由注册表生成（见文件头命令），是特征/算子元数据的唯一文档化"
        "视图；手工维护的名单已退役（P7 D3）。语义类型与推荐周期目前仅为"
        "**描述性**元数据：进入搜索合法性判定是 Phase E 独立预注册契约的"
        "事项。实测覆盖率与相关簇依赖校准数据，不在本生成物中。"
    )
    add("")

    # --- features ---------------------------------------------------------
    add(f"## 1. 基础特征（{len(FEATURE_NAMES)} 个，按词表稳定顺序）")
    add("")
    add(
        "| 特征 | 家族 | Tier | PIT | 语义类型 | 推荐周期 | 预期方向 |"
        " 计算成本 | 依赖 | 归属研究域 | 可用时间规则 | 经济假设 |"
    )
    add("|---|---|---|---|---|---|---|---|---|---|---|---|")
    for name in FEATURE_NAMES:
        authored = FEATURE_METADATA[name]
        tier = tier_of_pit_level(pit_level_of(name)).value
        horizon = resolve_expected_horizon(name)
        deps = ", ".join(resolve_depends_on(name, authored)) or "—"
        add(
            f"| {name} "
            f"| {_family_of(name)} "
            f"| {tier} "
            f"| {pit_level_of(name).value} "
            f"| {authored.semantic_type.value} "
            f"| {horizon.value if horizon else '—'} "
            f"| {authored.expected_direction:+d} "
            f"| {resolve_cost(name, authored).value} "
            f"| {deps} "
            f"| {_feature_domain(name)} "
            f"| {authored.availability_rule} "
            f"| {authored.hypothesis} |"
        )
    add("")

    # --- operators ----------------------------------------------------------
    add(f"## 2. 公式算子（{len(OPS_CONFIG)} 个，按 OPS_CONFIG 顺序）")
    add("")
    add(
        "arity 与实现来自 `OPS_CONFIG`（单一权威，此处派生不复制的导入约束见"
        " `ashare_model/operator_registry.py` 的 import 断言）。"
    )
    add("")
    add(
        "| 算子 | arity | 类别 | 输入语义（按参数位） | 输出语义 |"
        " 计算成本 | 数值稳定性 |"
    )
    add("|---|---|---|---|---|---|---|")
    for name, _, arity in OPS_CONFIG:
        meta = OPERATOR_REGISTRY[name]
        inputs = " ; ".join(
            "/".join(t.value for t in arg_types) for arg_types in meta.inputs
        )
        output = meta.output.value if meta.output is not None else "（Phase E 定）"
        add(
            f"| {name} "
            f"| {arity} "
            f"| {meta.category.value} "
            f"| {inputs} "
            f"| {output} "
            f"| {meta.cost.value} "
            f"| {meta.stability} |"
        )
    add("")

    # --- domain summary -----------------------------------------------------
    add("## 3. 研究域归属摘要")
    add("")
    add("| 研究域 | 特征数 | 默认执行点 |")
    add("|---|---|---|")
    for domain in RESEARCH_DOMAINS.values():
        freq, horizon = domain.default_execution()
        add(f"| {domain.id} | {len(domain.features)} | ({freq}, {horizon}) |")
    add("")
    add(
        "不在任何域的特征：`NORTHBOUND_CHG`（deprecated，中性占位，"
        "promotion_allowed=False）。"
    )
    add("")
    return "\n".join(lines)


def _family_of(name: str) -> str:
    """Family via the registry's single derivation path (no second copy)."""

    return family_of(name)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 when the committed document is stale",
    )
    args = parser.parse_args(argv)

    document = build_document()
    if args.check:
        current = (
            DOC_PATH.read_text(encoding="utf-8") if DOC_PATH.exists() else None
        )
        if current != document:
            print(
                "registry docs drift: regenerate with "
                "`python scripts/generate_registry_docs.py`",
                file=sys.stderr,
            )
            return 1
        print(f"{DOC_PATH.name} is in sync with the registries")
        return 0
    DOC_PATH.write_text(document, encoding="utf-8")
    print(f"wrote {DOC_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
